### ISSUE TITLE
[Feature Request]: Some issues and ideas

### ISSUE THREAD

**Issue by ayxj0** [InterestingDarkness/EdgeGPT#10]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

"When I received an error message saying 'messages' while using your script, I logged into the official Bing and found that I had reached the 24-hour information limit. However, strangely, I hadn't even had ten conversations. So I guess my account was restricted by Microsoft. But when I used the Pandora script, I found that I could still have conversations. So I guess it might be due to the difference between your script using 'chat' and the Pandora script using 'SearchQuery'."

### Proposed workflow

1. Go to ....
2. Press ....
3. ...
none

**Comment by InterestingDarkness** [comment]
SearchQuery and Chat have separate limitations, if one doesn't work then you can try another
