### ISSUE TITLE
Some sharing on edgegptUI color matching

### ISSUE THREAD

**Issue by NAOXUAN4** [InterestingDarkness/EdgeGPT#11]
After using it for a period of time, I felt like 'everything is back', it feels like using bing in March,but after using for a long time I felt that the default white+black interface was very eye-catching, and a large part of Sydney's search process greatly affected chatting. Therefore, I made some modifications to the color scheme and interface size, hoping to provide a reference
[https://github.com/NAOXUAN4/EdgeGPT/blob/MoveToChatSydney/new%20color.png](url)
[https://github.com/NAOXUAN4/EdgeGPT/blob/MoveToChatSydney/gui.py](url)

**Comment by InterestingDarkness** [comment]
You can follow this project https://github.com/juzeon/SydneyQt
