### ISSUE TITLE
Can you open a PR on EdgeGPT to integrate jailbreak?

### ISSUE THREAD

**Issue by scmanjarrez** [InterestingDarkness/EdgeGPT#2]
Hi, can you open a PR in EdgeGPT repo to integrate your jailbreak implementation? Adding your implementation to EdgeGPT would be very beneficial.

**Comment by InterestingDarkness** [comment]
https://github.com/acheong08/EdgeGPT/issues/94#issuecomment-1480631611
Looks like they don't accept jailbreak, and I removed ImageGen. You can fork my repo and submit a PR to them.

**Comment by scmanjarrez** [comment]
Oh, didn't know acheong wanted vanilla. Thank you.

**Comment by InterestingDarkness** [comment]
I'll open a PR to integrate parts of jailbreak, such as anti-revoke

**Comment by InterestingDarkness** [comment]
Rebased my project, now it's using almost original EdgeGPT
