### ISSUE TITLE
Can you add a shortcut key function?

### ISSUE THREAD

**Issue by ayxj0** [InterestingDarkness/EdgeGPT#3]
Can you add a shortcut key function? I'm used to pressing the ENTER key to send messages directly, instead of using the mouse to click.

**Comment by InterestingDarkness** [comment]
Completed https://github.com/InterestingDarkness/EdgeGPT/commit/cef0844415a2514c09e33e9ab14c13a05f1e25f0

**Comment by ayxj0** [comment]
thanks.
