### ISSUE TITLE
[Bug]: Some promts in GUI doesn't work properly

### ISSUE THREAD

**Issue by headstone1990** [InterestingDarkness/EdgeGPT#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

For some promts, possibly where a rather long output is expected, or perhaps for some other reason, I'm not sure, I get this. Console is empty, no logs
![image](https://user-images.githubusercontent.com/8353922/235710358-adab7f07-32d8-4a6c-aace-208e3456138d.png)
But if i add "put it in a code block" instruction, all works fine
![image](https://user-images.githubusercontent.com/8353922/235711528-14f28fba-8728-451b-8e8e-2f0f486c9f1f.png)

### Steps to reproduce the problem

...

### What should have happened?

...

### Version where the problem happens

latest version

### Command Line Arguments

```Shell
...
```

### Console logs

```Shell
...
```

**Comment by InterestingDarkness** [comment]
Yes it's a Bing bug, the AI was trying to generate a image instead of code

**Comment by headstone1990** [comment]
Promt for test: "Write a script for comedian movie"
