### ISSUE TITLE
[Feature Request]: Support Web GUI

### ISSUE THREAD

**Issue by VMTask** [InterestingDarkness/EdgeGPT#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Add a web GUI.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by InterestingDarkness** [comment]
Good idea. If we have a GUI, we can talk to Sydney on Android. I hope someone create a new project. And I prefer not to use Node.js. Use Python backend only.

**Comment by InterestingDarkness** [comment]
I think this issue is unrelated to EdgeGPT. We can write all the logic in JavaScript except creating conversation because of CORS.

**Comment by VMTask** [comment]
Why not use Node.js?

**Comment by InterestingDarkness** [comment]
My preference. Also there's already
https://github.com/waylaidwanderer/PandoraAI

2023年5月3日(水) 14:44 VMTask ***@***.***>:

**Comment by InterestingDarkness** [comment]
completed https://github.com/InterestingDarkness/ChatSydney
