### ISSUE TITLE
[Feature Request]: Issues with AI-generated suggestions

### ISSUE THREAD

**Issue by ayxj0** [InterestingDarkness/EdgeGPT#9]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Can you add a toggle to choose whether or not to generate AI suggestions? I think the previous version was clean and simple, which was nice. This not only increases the word count of the chat log, but also makes the appearance somewhat cluttered.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...
none

**Comment by InterestingDarkness** [comment]
https://github.com/juzeon/SydneyQt implemented it
